<!--
 * @Author              : qxp
 * @Date                : 2021-11-02 15:16:10
 * @LastEditors         : Please set LastEditors
 * @LastEditTime        : 2021-11-02 15:19:04
 * @FilePath            : \new\6 Es6\8 迭代器和生成器\3 async  await函数\5 异常捕获.html
-->
https://libin1991.github.io/2019/01/25/async-await%E4%BC%98%E9%9B%85%E7%9A%84%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95/

<script>
    (async () => {
        const fetchData = async () => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve('fetch data is me')
                }, 1000)
            })
        }

        // 抽离成公共方法
        const awaitWrap = (promise) => {
            return promise
                .then(data => [null, data])
                .catch(err => [err, null])
        }

        const [err, data] = await awaitWrap(fetchData())
        console.log('err', err)
        console.log('data', data)
        // err null// data fetch data is me
    })()


    functionawaitWrap < T, U = any > (promise: Promise < T >): Promise < [U | null, T | null] > {
        return promise.then < [null, T] > ((data: T) => [null, data]).catch < [U, null] > (err => [err, null])
    }




    // to.js
    export default function to(promise) {
        return promise.then(data => { return [null, data]; }).catch(err => [err]);
    }

    import to from './to.js';

    async function asyncTask() {
        let err, user, savedTask;

        [err, user] = await to(UserModel.findById(1));
        if (!user) throw new CustomerError('No user found');

        [err, savedTask] = await to(TaskModel({ userId: user.id, name: 'Demo Task' }));
        if (err) throw new CustomError('Error occurred while saving task');

        if (user.notificationsEnabled) {
            const [err] = await to(NotificationService.sendNotification(user.id, 'Task Created'));
            if (err) console.error('Just log the error and continue flow');
        }
    }


    
</script>